### ISSUE TITLE
Running Streaming Data Loader produces import error

### ISSUE THREAD

**Issue by kwuz** [ODM2/ODM2StreamingDataLoader#53]
![image](https://cloud.githubusercontent.com/assets/15348288/22356184/acc917be-e3ec-11e6-9ff0-1a1e2e2a43d0.png)

![image](https://cloud.githubusercontent.com/assets/15348288/22356195/bbaf29c6-e3ec-11e6-9224-55435a3389ff.png)

**Comment by farrieta9** [comment]
I get the same error but with wx instead of omd2api

**Comment by farrieta9** [comment]
It seems like we are getting these import errors because our libraries are not on the global environment. If I still wxpython outside an environment I get a pandas import error and if I install pandas then I get the next import error. Do we want to keep the command line argument? Would this issue be fixed if we make a release because the environment is packaged?

**Comment by farrieta9** [comment]
Fixed on Feb 8
