### ISSUE TITLE
CensorCodeCV incorrectly assigned

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODM2StreamingDataLoader#74]
All of the data values that I have loaded so far are assigned a CensorCodeCV of non-detect, which is incorrect. Moreover, I'm not sure how this is assigned or selected, so i don't know how I might change it?

![image](https://cloud.githubusercontent.com/assets/5023186/24983028/c2d89eb2-1fa1-11e7-927d-c5306d812c81.png)

**Comment by sreeder** [comment]
@kwuz I believe the censor code is being statically set. and the previous developer set it to non-detect for testing purposes so that he could easily find and delete his test data. You should be able to just change the string he is setting it too. 
@AmberSJones should the user be able to set this somewhere in the SDL? or do we want it to be set to a default value.

**Comment by AmberSJones** [comment]
I think it should be set to a default value- not censored.

**Comment by sreeder** [comment]
this has been addressed
