### ISSUE TITLE
Executable is not running

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODM2StreamingDataLoader#79]
I've been unable to get the executable to run via the Windows task scheduler or manually. This error flashes on and off, but I was able to capture it with a screenshot.
<img width="1680" alt="screen shot 2017-04-13 at 8 19 10 am" src="https://cloud.githubusercontent.com/assets/5023186/25008862/223fca6c-2022-11e7-9ba8-e2c6eabc1d36.png">

**Comment by farrieta9** [comment]
![capture](https://cloud.githubusercontent.com/assets/12265327/25640001/3552dc56-2f4b-11e7-8b74-5455ac91f4ab.PNG)

If you double click on the StreamDataLoaderWizard.exe you'll get that error and it's because it expects an input file. Try running the file from the command line. From the command line navigate to it and then run a command like the one below.

./StreamingDataLoader.exe -c C:\Users\Francisco\Desktop\SDL Folder\LoadTest.yaml

I gave it a yaml file as an argument.

**Comment by sreeder** [comment]
@AmberSJones  @horsburgh  this is more a question of functionality, do we want a default location that the code looks for a setup file if none is sent in as a parameter? Other than that I think it is just an issue of figuring out how to send in command line arguments when running from the windows task scheduler. [Here](https://superuser.com/questions/270643/how-to-pass-an-argument-to-a-windows-scheduled-task-with-spaces-in-it ) is a link to an issue where they show how to add arguments. 
<img width="687" alt="screen shot 2017-06-14 at 3 25 59 pm" src="https://user-images.githubusercontent.com/4721940/27155341-d7b4ac7c-5115-11e7-91f6-fa48f2429212.png">

**Comment by horsburgh** [comment]
I think the default location to look for a setup file should be the same folder as the code. The command line parameter should be capable of using any setup file from any path, but if one is not specified, look in the folder where the code is located. If there's not one there, throw an error.

**Comment by kwuz** [comment]
"base case" of searching for a default yaml file in the current working directory if no arguments are provided is added. Executable will still fail if no yaml file is present, and does not check if yaml file is the correct configuration for the program to run.

**Comment by kwuz** [comment]
Ready for testing, branch issue_79
